{% set name = "gstreamer-orc" %}
{% set version = "0.4.30" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gstreamer.freedesktop.org/data/src/orc/orc-{{version}}.tar.xz
  sha256: ba41b92146a5691cd102eb79c026757d39e9d3b81a65810d2946a1786a1c4972

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make

test:
  commands:
    - test -f ${PREFIX}/lib/liborc-0.4${SHLIB_EXT}  # [unix]
    - orcc --help
    - orc-bugreport --help
 
about:
  home: https://gstreamer.freedesktop.org/modules/orc.html
  license: Custom
  license_file: COPYING
  summary: 'Optimized Inner Loop Runtime Compiler'

extra:
  recipe-maintainers:
    - sebastian-luna-valero
