{% set name = "gstreamer-orc" %}
{% set version = "0.4.42" %}
{% set majmin = ".".join(version.split(".")[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gstreamer.freedesktop.org/data/src/orc/orc-{{ version }}.tar.xz
  sha256: 7ec912ab59af3cc97874c456a56a8ae1eec520c385ec447e8a102b2bd122c90c
  patches:
    - 0001-Add-install_rpath-to-meson.build.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - meson
    - ninja

test:
  requires:
    - chrpath  # [linux]
  commands:
    - test -f ${PREFIX}/lib/liborc-{{ majmin }}${SHLIB_EXT}  # [unix]
    - if not exist %PREFIX%\\Library\\bin\\orc-{{ majmin }}-0.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\orc-{{ majmin }}.lib exit 1  # [win]
    - chrpath -l ${PREFIX}/lib/liborc-{{ majmin }}.so      | grep -qF 'RPATH=$ORIGIN/.'  # [linux]
    - chrpath -l ${PREFIX}/lib/liborc-test-{{ majmin }}.so | grep -qF 'RPATH=$ORIGIN/.'  # [linux]
    - orcc --help
    - orc-bugreport --help

about:
  home: https://gstreamer.freedesktop.org/modules/orc.html
  license: BSD-2-Clause AND BSD-3-Clause
  license_file: COPYING
  summary: Optimized Inner Loop Runtime Compiler

extra:
  recipe-maintainers:
    - ryanvolz
    - sebastian-luna-valero
