{% set name = "gstreamer-orc" %}
{% set version = "0.4.32" %}
{% set majmin = ".".join(version.split(".")[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gstreamer.freedesktop.org/data/src/orc/orc-{{ version }}.tar.xz
  sha256: a66e3d8f2b7e65178d786a01ef61f2a0a0b4d0b8370de7ce134ba73da4af18f0
  patches:
    - 0001-Add-install_rpath-to-meson.build.patch
    # next patch is upstream, should be able to remove after 0.4.32
    - 0002-Fix-powerpc-build-with-kernel-lt-411.patch

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - meson
    - ninja

test:
  requires:
    - chrpath  # [linux]
  commands:
    - test -f ${PREFIX}/lib/liborc-{{ majmin }}${SHLIB_EXT}  # [unix]
    - if not exist %PREFIX%\\Library\\bin\\orc-{{ majmin }}.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\orc-{{ majmin }}.lib exit 1  # [win]
    - chrpath -l ${PREFIX}/lib/liborc-{{ majmin }}.so      | grep -qF 'RPATH=$ORIGIN/.'  # [linux]
    - chrpath -l ${PREFIX}/lib/liborc-test-{{ majmin }}.so | grep -qF 'RPATH=$ORIGIN/.'  # [linux]
    - orcc --help
    - orc-bugreport --help

about:
  home: https://gstreamer.freedesktop.org/modules/orc.html
  license: BSD-2-Clause AND BSD-3-Clause
  license_file: COPYING
  summary: Optimized Inner Loop Runtime Compiler

extra:
  recipe-maintainers:
    - ryanvolz
    - sebastian-luna-valero
