{% set name = "gstreamer-orc" %}
{% set version = "0.4.31" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gstreamer.freedesktop.org/data/src/orc/orc-{{version}}.tar.xz
  sha256: a0ab5f10a6a9ae7c3a6b4218246564c3bf00d657cbdf587e6d34ec3ef0616075

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - meson

test:
  commands:
    - test -f ${PREFIX}/lib/liborc-0.4${SHLIB_EXT}  # [unix]
    - orcc --help
    - orc-bugreport --help
 
about:
  home: https://gstreamer.freedesktop.org/modules/orc.html
  license: Custom
  license_file: COPYING
  summary: 'Optimized Inner Loop Runtime Compiler'

extra:
  recipe-maintainers:
    - sebastian-luna-valero
