travis:
  secure:
    BINSTAR_TOKEN: Sns202clcQSOHN7eAtPMB0i9l27tSWhS6bs3pgta0Hf3bQHZ2sb60UhXuPyyiPnaKcFYQ/6CWY3zJGSuejx4KVNqzRNKk0WGs1ayMN4A92eiXY8xpM+D6Fi7t5aqATGZL0zexaXe71JGntdzmcDFghEIsfswCQb32OxhHyBUluX5uAHINjxsAO378HspEnuF3MMAKexiB8MOZ9855DQcJbe5YCw+As31ELjlFLQuhjxs5kSwl3kNe9NZu4UOq5XY9SN761gLrmice/fXJXmy36F9b7Kt51w1nSELJcgnrKkMpWkLI1ThjYCVc+qdPwcYIMr2Z+CB4eN/SGr2tkSwOVjmHRvTh3odo1CFUgruLAl2bFSRRDMdxi1CFHP/yKRyT2DX05T/i70VOHHtJJnBu/14ucnKfxAbD6X7f5udC3fj4RBPVHMdW4EjGs3peiLqJTyFS/eMMrbbwX1QshRiVQnridIi0KMm350vi4UkwnoDvH4gPl5Du5GFx7xyxRkcnjLEzkwx2hHYfl7zm+1iaxjPKBvkNer4PsjleNWYFp/J9HihAYg2Uo4EVnG2q8wD08w7Z50T6L0R3AVK422RDrtxzohq76ddiz4zlblSdF5adhbKwVSSII8lEI+fzQPWhQReSow5CAi/3cCwqRiJXn72GBsQMc3UEblKPOoebjQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
