travis:
  secure:
    BINSTAR_TOKEN: goyx6FiAuQNjw288Ry3d1ejw/eitseFeQWTPpUHtjlh0MfgbXYkTuob1FjZS1VzbBKqnEKLTAr3xk+9vR+I3SdmXOG3kPdT8lrsuLjdkWG4Nw8DGre5uz2jU+Djk0QSRZ4rn3SzW53kME5Rw+rXVnYwUKVjwo3U+RKv0nH7BTkfY0WflhiFx5UIiY/3EXDeW4+41hR0d1GwyCQtomQApiQe52a38osqZM/haje9BgfG0xfUzefRyyoUunovFvo6l8MzyJz426T2WLn0CHE5ccg/b8myfos6pDbjoOerbtWbZb+o0Io67rDffOQDTdIhEoaR912K8hHvvf3g2ZZNavhuHlQ9Dsa8OGdAudj29V7IbdHiDplU/tK8JcvGl433NZXavG1CbM8DXkLjhPNixpCFH66MJ2uOO1Q+xq0b5oyaXcdI9zQmHcXUPoYXfKimK0BgutaUg0D0S1c2KJBJjRjO+gmnB7Dz2rOh0874lU9MGfm3rqEOh6XIJb8EHand5PMLzxzyWMip5j0Wnccl/qL179OsxiaK80Umr1NFWQ1cpiiuQqrpHe1Gqk9d0/Pr/yO3EstVkErlF22y0zQ0vA73tLtRXkdkTiqMz9HBjhv6SZhk1RqUUJupZD+1bxmayUdxdCC4xHM2gL6W17cPI4PctgBU4KZs2mKu/38azZbA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
